server:
  port: 8081

spring:
  application:
    name: alibaba-ai-demo

  ai:
    model:
      chat: ollama
    ollama:
      chat:
        options:
          model: qwen3:4b   # 模型名称
      base-url: http://localhost:11434